import { useState } from "react";
import { LoaderCircle, ShieldCheck, X } from "lucide-react";
import { submitAccountKyc } from "../lib/auth-client";

export default function KycAccountModal({ accessToken, onClose, onSuccess, user }) {
  const [values,setValues]=useState({fullName:user.fullName??"",dateOfBirth:"",email:user.email??"",phone:user.phone??"",address:user.address??"",identityNumber:user.identityNumber??"",identityIssuedAt:""});
  const [files,setFiles]=useState({}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  async function submit(event){event.preventDefault();setError("");if(!files.identityFront||!files.identityBack||!files.selfie){setError("Vui lòng tải đủ CCCD mặt trước, mặt sau và ảnh selfie.");return}setSaving(true);try{const response=await submitAccountKyc(accessToken,values,files);onSuccess(response.message)}catch(e){setError(e.message)}finally{setSaving(false)}}
  const inputClass="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-green-500";
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><form className="mx-auto my-6 w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl" onSubmit={submit}><div className="flex items-start justify-between"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-full bg-green-50 text-green-600"><ShieldCheck/></span><div><h2 className="text-xl font-bold">Xác thực tài khoản</h2><p className="mt-1 text-sm text-slate-500">Thông tin được dùng để đối chiếu với CCCD. Chưa yêu cầu OTP/email.</p></div></div><button type="button" onClick={onClose}><X/></button></div>
  <div className="mt-6 grid gap-4 md:grid-cols-2">{[["fullName","Họ và tên","text"],["dateOfBirth","Ngày sinh","date"],["email","Email","email"],["phone","Số điện thoại","tel"],["address","Địa chỉ","text"],["identityNumber","Số CCCD","text"],["identityIssuedAt","Ngày cấp","date"]].map(([key,label,type])=><label className={key==="address"?"md:col-span-2 text-sm":"text-sm"} key={key}>{label}<input className={inputClass} required type={type} value={values[key]} onChange={(e)=>setValues({...values,[key]:e.target.value})}/></label>)}</div>
  <div className="mt-6 grid gap-4 md:grid-cols-3">{[["identityFront","CCCD mặt trước"],["identityBack","CCCD mặt sau"],["selfie","Ảnh selfie"]].map(([key,label])=><label className="rounded-2xl border border-dashed p-4 text-sm" key={key}><b className="block">{label}</b><span className="mt-1 block text-xs text-slate-500">JPG, PNG hoặc WEBP · tối đa 10MB</span><input accept="image/jpeg,image/png,image/webp" className="mt-3 block w-full text-xs" required type="file" onChange={(e)=>setFiles({...files,[key]:e.target.files?.[0]})}/></label>)}</div>
  {error?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<div className="mt-6 flex justify-end gap-3"><button className="rounded-xl border px-5 py-2.5 text-sm font-semibold" type="button" onClick={onClose}>Hủy</button><button className="flex items-center gap-2 rounded-xl bg-[#32A452] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60" disabled={saving}>{saving?<LoaderCircle className="size-4 animate-spin"/>:null}{saving?"Đang gửi...":"Gửi hồ sơ"}</button></div></form></div>;
}
