import { useState } from "react";
import { LoaderCircle, X } from "lucide-react";
import { submitListingVerification } from "../lib/property-client";

export default function ListingVerificationModal({ accessToken, listing, onClose, onSuccess }) {
  const [documentType,setDocumentType]=useState("ownership_certificate"); const [files,setFiles]=useState([]); const [note,setNote]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  async function submit(e){e.preventDefault();if(!files.length){setError("Vui lòng chọn ít nhất một giấy tờ.");return}setSaving(true);setError("");try{const r=await submitListingVerification(accessToken,listing.id,documentType,files,note);onSuccess(r.message)}catch(err){setError(err.message)}finally{setSaving(false)}}
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/40 p-4"><form className="w-full max-w-xl rounded-3xl bg-white p-6" onSubmit={submit}><div className="flex justify-between"><div><h2 className="text-xl font-bold">Xác thực bất động sản</h2><p className="mt-1 text-sm text-slate-500 line-clamp-1">{listing.title}</p></div><button type="button" onClick={onClose}><X/></button></div><label className="mt-5 block text-sm">Loại giấy tờ<select className="mt-1 h-11 w-full rounded-xl border px-3" value={documentType} onChange={(e)=>setDocumentType(e.target.value)}><option value="ownership_certificate">Sổ hồng</option><option value="sale_contract">Hợp đồng mua bán</option><option value="sublease_contract">Hợp đồng thuê lại</option><option value="authorization_letter">Giấy ủy quyền</option></select></label><label className="mt-4 block rounded-xl border border-dashed p-4 text-sm">Tải giấy tờ (tối đa 10 tệp)<input accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-3 block w-full text-xs" multiple required type="file" onChange={(e)=>setFiles(Array.from(e.target.files??[]))}/></label><label className="mt-4 block text-sm">Ghi chú<textarea className="mt-1 min-h-20 w-full rounded-xl border p-3" value={note} onChange={(e)=>setNote(e.target.value)}/></label>{error?<p className="mt-3 text-sm text-red-600">{error}</p>:null}<button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#32A452] py-3 font-semibold text-white disabled:opacity-60" disabled={saving}>{saving?<LoaderCircle className="size-4 animate-spin"/>:null}{saving?"Đang gửi...":"Gửi hồ sơ xác thực"}</button></form></div>;
}
